class IdentificadorEstado:
    def __init__(self):
        self.estados = {
            ("AAA", "BEZ"): "Paraná",
            ("BFA", "GKI"): "São Paulo",
            ("GKJ", "HOK"): "Minas Gerais",
            ("HOL", "HQE"): "Maranhão",
            ("HQF", "HTW"): "Mato Grosso do Sul",
            ("HTX", "HZA"): "Ceará",
            ("HZB", "IAP"): "Sergipe",
            ("IAQ", "JDO"): "Rio Grande do Sul",
            ("JDP", "JKR"): "Distrito Federal",
            ("JKS", "JSZ"): "Bahia",
            ("JTA", "JWE"): "Pará",
            ("JWF", "JXY"): "Amazonas",
            ("JXZ", "KAU"): "Mato Grosso",
            ("KAV", "KFC"): "Goiás",
            ("KFD", "KME"): "Pernambuco",
            ("KMF", "LVE"): "Rio de Janeiro",
            ("LVF", "LWQ"): "Piauí",
            ("LWR", "MMM"): "Santa Catarina",
            ("MMN", "MOW"): "Paraíba",
            ("MOX", "MTZ"): "Espírito Santo",
            ("MUA", "MVK"): "Alagoas",
            ("MVL", "MXG"): "Tocantins",
            ("MXH", "MZM"): "Rio Grande do Norte",
            ("MZN", "NAG"): "Acre",
            ("NAH", "NBA"): "Roraima",
            ("NBB", "NEH"): "Rondônia",
            ("NEI", "NFB"): "Amapá",
            ("NFC", "NGZ"): "Goiás",
            ("NHA", "NHT"): "Maranhão",
            ("NHU", "NIX"): "Piauí",
            ("NIY", "NJW"): "Mato Grosso",
            ("NJX", "NLU"): "Goiás",
            ("NLV", "NMO"): "Alagoas",
            ("NMP", "NNI"): "Maranhão",
            ("NNJ", "NOH"): "Rio Grande do Norte",
            ("NOI", "NPB"): "Amazonas",
            ("NPC", "NPQ"): "Mato Grosso",
            ("NPR", "NQK"): "Paraíba",
            ("NQL", "NRE"): "Ceará",
            ("NRF", "NSD"): "Mato Grosso do Sul",
            ("NSE", "NTC"): "Pará",
            ("NTD", "NTW"): "Bahia",
            ("NTX", "NUG"): "Mato Grosso",
            ("NUH", "NUL"): "Roraima",
            ("NUM", "NVF"): "Ceará",
            ("NVG", "NVN"): "Sergipe",
            ("NVO", "NWR"): "Goiás",
            ("NWS", "NXQ"): "Maranhão",
            ("NXR", "NXT"): "Acre",
            ("NXU", "NXW"): "Pernambuco",
            ("NXX", "NYG"): "Minas Gerais",
            ("NYH", "NZZ"): "Bahia",
            ("OAA", "OAO"): "Amazonas",
            ("OAP", "OBS"): "Mato Grosso",
            ("OBT", "OCA"): "Pará",
            ("OCB", "OCU"): "Ceará",
            ("OCV", "ODT"): "Espírito Santo",
            ("ODU", "OEI"): "Piauí",
            ("OEJ", "OES"): "Sergipe",
            ("OET", "OFH"): "Paraíba",
            ("OFI", "OFW"): "Pará",
            ("OFX", "OGG"): "Paraíba",
            ("OGH", "OHA"): "Goiás",
            ("OHB", "OHK"): "Alagoas",
            ("OHL", "OHW"): "Rondônia",
            ("OHX", "OIQ"): "Ceará",
            ("OIR", "OJQ"): "Maranhão",
            ("OJR", "OKC"): "Rio Grande do Norte",
            ("OKD", "OKH"): "Santa Catarina",
            ("OKI", "OLG"): "Bahia",
            ("OLH", "OLN"): "Tocantins",
            ("OLO", "OMH"): "Minas Gerais",
            ("OMI", "OOF"): "Goiás",
            ("OOG", "OOU"): "Mato Grosso do Sul",
            ("OOV", "ORC"): "Minas Gerais",
            ("ORD", "ORM"): "Alagoas",
            ("ORN", "OSV"): "Ceará",
            ("OSW", "OTZ"): "Pará",
            ("OUA", "OUE"): "Piauí",
            ("OUF", "OVD"): "Bahia",
            ("OVE", "OVF"): "Espírito Santo",
            ("OVG", "OVG"): "Acre",
            ("OVH", "OVL"): "Espírito Santo",
            ("OVM", "OVV"): "Espírito Santo",
            ("OVW", "OVY"): "Distrito Federal",
            ("OVZ", "OWG"): "Piauí",
            ("OWH", "OXK"): "Rio Grande do Norte",
            ("OXL", "OXL"): "Minas Gerais",
            ("OXM", "OXM"): "Rondônia",
            ("OXN", "OXN"): "Amazonas",
            ("OXO", "OXO"): "Alagoas",
            ("OXP", "OXP"): "Paraíba",
            ("OXQ", "OXZ"): "Acre",
            ("OYA", "OYC"): "Maranhão",
            ("OYD", "OYK"): "Tocantins",
            ("OYL", "OYZ"): "Espírito Santo",
            ("OZA", "OZA"): "Pernambuco",
            ("OZB", "OZB"): "Ceará",
            ("OZC", "OZV"): "Sergipe",
            ("OZW", "PBZ"): "Bahia",
            ("PCA", "PED"): "Distrito Federal",
            ("PEE", "PFQ"): "Pernambuco",
            ("PFR", "PGK"): "Pernambuco",
            ("PGL", "PGU"): "Pernambuco",
            ("PGV", "PGZ"): "Pernambuco",
            ("PHA", "PHZ"): "Pernambuco",
            ("PIA", "PIZ"): "Amazonas",
            ("PJA", "PLZ"): "Piauí",
            ("PMA", "POZ"): "Bahia",
            ("PPA", "PPZ"): "Ceará",
            ("PQA", "PRZ"): "Espírito Santo",
            ("PSA", "PTZ"): "Goiás",
            ("PUA", "PZZ"): "Maranhão",
            ("QAA", "QAZ"): "Minas Gerais",
            ("QBA", "QCZ"): "Mato Grosso do Sul",
            ("QDA", "QEZ"): "Mato Grosso",
            ("QFA", "QFZ"): "Pará",
            ("QGA", "QGZ"): "Paraíba",
            ("QHA", "QJZ"): "Rio Grande do Norte",
            ("QKA", "QKM"): "Santa Catarina",
            ("QKN", "QKZ"): "Tocantins",
            ("QLA", "QLM"): "Sergipe",
            ("QLN", "QLT"): "Alagoas",
            ("QLU", "QLZ"): "Amapá",
            ("QMA", "QMP"): "Sergipe",
            ("QMQ", "QQZ"): "Minas Gerais",
            ("QRA", "QRA"): "Rondônia",
            ("QRB", "QRM"): "Espírito Santo",
            ("QRN", "QRZ"): "Piauí",
            ("QSA", "QSM"): "Paraíba",
            ("QSN", "QSZ"): "São Paulo",
            ("QTA", "QTJ"): "Rondônia",
            ("QTK", "QTM"): "Santa Catarina",
            ("QTN", "QTS"): "Goiás",
            ("QTT", "QTT"): "Alagoas",
            ("QTU", "QTZ"): "Bahia",
            ("QUA", "QUZ"): "Minas Gerais",
            ("QVA", "QVZ"): "Pará",
            ("QWA", "QWF"): "Tocantins",
            ("QWG", "QWL"): "Alagoas",
            ("QWM", "QWQ"): "Acre",
            ("QWR", "QXZ"): "Minas Gerais",
            ("QYA", "QYZ"): "Pernambuco",
            ("QZA", "QZZ"): "Amazonas",
            ("RAA", "RAJ"): "Santa Catarina",
            ("RAK", "RAZ"): "Mato Grosso",
            ("RBA", "RBJ"): "Espírito Santo",
            ("RBK", "RCN"): "Goiás",
            ("RCO", "RDR"): "Bahia",
            ("RDS", "REB"): "Santa Catarina",
            ("REC", "REV"): "Distrito Federal",
            ("REW", "REZ"): "Mato Grosso do Sul",
            ("RFA", "RGD"): "Minas Gerais",
            ("RGE", "RGM"): "Rio Grande do Norte",
            ("RGN", "RGN"): "Rio Grande do Norte",
            ("RGO", "RGU"): "Alagoas",
            ("RGV", "RGZ"): "Sequências ainda não definidas",
            ("RHA", "RHZ"): "Paraná",
            ("RIA", "RIN"): "Ceará",
            ("RIO", "RIO"): "Rio de Janeiro",
            ("RIP", "RKV"): "Rio de Janeiro",
            ("RKW", "RLP"): "Santa Catarina",
            ("RLQ", "RMC"): "Paraíba",
            ("RMD", "RNZ"): "Minas Gerais",
            ("ROA", "ROZ"): "Maranhão",
            ("RPA", "RQL"): "Bahia",
            ("RQM", "RQV"): "Espírito Santo",
            ("RQW", "RRH"): "Sergipe",
            ("RRI", "RRZ"): "Mato Grosso",
            ("RSA", "RSF"): "Tocantins",
            ("RSG", "RST"): "Piauí",
            ("RSU", "RSZ"): "Rondônia",
            ("RTA", "RVZ"): "Minas Gerais",
            ("RWA", "RWJ"): "Mato Grosso do Sul",
            ("RWK", "RXD"): "Pará",
            ("RXE", "RXJ"): "Sequências ainda não definidas",
            ("RXK", "RYI"): "Santa Catarina",
            ("RYJ", "RYZ"): "Sequências ainda não definidas",
            ("RZA", "RZD"): "Roraima",
            ("RZE", "RZZ"): "Pernambuco",
            ("SAA", "SAJ"): "Alagoas",
            ("SAK", "SAM"): "Amapá",
            ("SAN", "SBV"): "Ceará",
            ("SBW", "SDS"): "Goiás",
            ("SDT", "ZZZ"): "Sequências ainda não definidas"
        }


    def identificar_estado(self, placa):
        prefixo = placa[:3]
        for intervalo, estado in self.estados.items():
            if str(intervalo[0]) <= placa <= str(intervalo[1]):
                return estado

        return "Estado não encontrado"
